on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: saurabhregistry.azurecr.io
        username: ${{ secrets.acr_saurabhregistry_username }}
        password: ${{ secrets.acr_saurabhregistry_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/client" -f  "client/Dockerfile" -t saurabhregistry.azurecr.io/saurabhcluster:${{ github.sha }} --label dockerfile-path=client/Dockerfile
        docker push saurabhregistry.azurecr.io/saurabhcluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_saurabhcluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep saurabhcluster8eb3 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace saurabhcluster8eb3`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: saurabhcluster8eb3
        container-registry-url: saurabhregistry.azurecr.io
        container-registry-username: ${{ secrets.acr_saurabhregistry_username }}
        container-registry-password: ${{ secrets.acr_saurabhregistry_password }}
        secret-name: saurabhclustdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: saurabhcluster8eb3
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          saurabhregistry.azurecr.io/saurabhcluster:${{ github.sha }}
        imagepullsecrets: |
          saurabhclustdockerauth
